---
title: "Clean"
author: "Joshua Berry"
date: "1/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(foreign)
library(haven)
library(tidyverse)
library(readxl)
library(memisc)
library(rstanarm)
library(ggridges)
library(gtsummary)
library(broom.mixed)
library(gt)
library(rockchalk)
```

## R Markdown

```{r}
anes_2016 <- 
read_sav("anes_timeseries_2016.sav") %>%
  as_factor() %>%
  select(V161008, V161009, V162005, V162004, 
         V162003, V162002, V162159, V161270, V161267x,V161310x, V161155) %>%
  rename(V161008 = days_watched_media, V161009 = attention_to_media, 
         V162005 = newspaper_count, V162004 = internet_count, 
         V162003 = radio_count, V162002 = tv_count, 
         V162159 = china_mil_threat, V161270 = education, V161267x = age, 
         V161310x = race, V161155 = party_id) %>%
  mutate(year = 2016) %>%
  mutate(china_mil_scale = case_when(china_mil_threat == "1. Major threat" ~ 1,
                                     china_mil_threat == "2. Minor threat" ~ 1,
                                     china_mil_threat == "3. Not a threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(days_watched_media = case_when(days_watched_media == "0. None" ~ 0,
                                     days_watched_media == "1. One day" ~ 1,
                                     days_watched_media == "2. Two days" ~ 2,
                                     days_watched_media == "3. Three days" ~ 3,
                                     days_watched_media == "4. Four days" ~ 4,
                                     days_watched_media == "5. Five days" ~ 5,
                                     days_watched_media == "6. Six days" ~ 6,
                                     days_watched_media == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "1. Less than 1st grade" ~ 0,
                                     education == "2. 1st, 2nd, 3rd or 4th grade" ~ 1,
                                     education == "3. 5th or 6th grade" ~ 2,
                                     education == "4. 7th or 8th grade" ~ 3,
                                     education == "5. 9th grade" ~ 5,
                                     education == "6. 10th grade" ~ 7,
                                     education == "7. 11th grade" ~ 9,
                                     education == "8. 12th grade no diploma" ~ 11,
                                     education == "9. High school graduate- high school diploma or equivalent (for example: GED)" ~ 15,
                                     education == "10. Some college but no degree" ~ 17,
                                     education == "11. Associate degree in college - occupational /vocational program" ~ 20,
                                     education == "12. Associate degree in college -- academic program" ~ 20,
                                     education == "13. Bachelor's degree (for example: BA, AB, BS)" ~ 25,
                                     education == "14. Master's degree (for example: MA, MS, MENG, MED, MSW, MBA) " ~ 28,
                                     education == "15. Professional school degree (for example: MD, DDS, DVM, LLB, JD)" ~ 31,
                                     education == "16. Doctorate degree (for example: PHD, EDD)" ~ 35,
                                     TRUE ~ NA_real_)) %>%
   mutate(age = case_when(age == "01. Age group 18-20" ~ 0,
                                     age == "02. Age group 21-24" ~ 1,
                                     age == "03. Age group 25-29" ~ 3,
                                     age == "04. Age group 30-34" ~ 6,
                                     age == "05. Age group 35-39" ~ 9,
                                     age == "06. Age group 40-44" ~ 12,
                                     age == "07. Age group 45-49" ~ 15,
                                     age == "08. Age group 50-54" ~ 18,
                                     age == "09. Age group 55-59" ~ 21,
                                     age == "10. Age group 60-64" ~ 24,
                                     age == "11. Age group 65-69" ~ 27,
                                     age == "12. Age group 70-74" ~ 30,
                                     age == "13. Age group 75 or older"  ~ 35,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "1. White, non-Hispanic" ~ "White",
                                     race == "2. Black, non-Hispanic" ~ "Black",
                                     race == "3. Asian, native Hawaiian or other Pacif Islr,non-Hispanic" ~ "Asian",
                                     race == "5. Hispanic" ~ "Hispanic",
                                     race == "6. Other non-Hispanic incl multiple races [WEB: blank 'Other' counted as a race]" ~ "Other",
                                     race == "4. Native American or Alaska Native, non-Hispanic" ~ "Native American",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "1. Democrat" ~ "Democrat",
                                     party_id == "2. Republican" ~ "Republican",
                                     party_id == "3. Independent" ~ "Independent",
                                     TRUE ~ NA_character_))



sixteen.china.mil.glm <- glm(china_mil_scale ~ days_watched_media + education + age + race + party_id,
                     data = anes_2016, family = "binomial")

summary(sixteen.china.mil.glm)
```



```{r}
anes_2012 <- 
read_sav("anes_timeseries_2012.sav") %>%
  as_factor() %>%
  select(prmedia_wkinews, prmedia_atinews, prmedia_wktvnws, prmedia_attvnews, 
         prmedia_wkpaprnws, prmedia_atpprnews, prmedia_wkrdnws, prmedia_atrdnews, dem_racecps_1st, dem_agegrp_iwdate_x, dem_edu, pid_self, china_econ, china_mil, medsrc_socmedia) %>%
    rename(prmedia_wkinews = days_read_internet_news, prmedia_wktvnws = days_watched_tv_news, 
         prmedia_wkpaprnws = days_read_paper_news, prmedia_wkrdnws = days_listened_radio_news,
         medsrc_socmedia = days_read_socmedia_news,
         dem_edu = education, dem_agegrp_iwdate_x = age, 
         dem_racecps_1st = race, pid_self = party_id) %>%
  mutate(year = 2012) %>%
  mutate(china_mil_scale = case_when(china_mil == "1. Major threat" ~ 1,
                                     china_mil == "2. Minor threat" ~ 1,
                                     china_mil == "3. Not a threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(china_econ_scale = case_when(china_econ == "1. Good" ~ 0,
                                     china_econ == "2. Bad" ~ 1,
                                     china_econ == "3. No effect" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(days_read_internet_news = case_when(days_read_internet_news == "0. None" ~ 0,
                                     days_read_internet_news == "1. One day" ~ 1,
                                     days_read_internet_news == "2. Two days" ~ 2,
                                     days_read_internet_news == "3. Three days" ~ 3,
                                     days_read_internet_news == "4. Four days" ~ 4,
                                     days_read_internet_news == "5. Five days" ~ 5,
                                     days_read_internet_news == "6. Six days" ~ 6,
                                     days_read_internet_news == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
  mutate(days_watched_tv_news = case_when(days_watched_tv_news == "0. None" ~ 0,
                                     days_watched_tv_news == "1. One day" ~ 1,
                                     days_watched_tv_news == "2. Two days" ~ 2,
                                     days_watched_tv_news == "3. Three days" ~ 3,
                                     days_watched_tv_news == "4. Four days" ~ 4,
                                     days_watched_tv_news == "5. Five days" ~ 5,
                                     days_watched_tv_news == "6. Six days" ~ 6,
                                     days_watched_tv_news == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
    mutate(days_read_paper_news = case_when(days_read_paper_news == "0. None" ~ 0,
                                     days_read_paper_news == "1. One day" ~ 1,
                                     days_read_paper_news == "2. Two days" ~ 2,
                                     days_read_paper_news == "3. Three days" ~ 3,
                                     days_read_paper_news == "4. Four days" ~ 4,
                                     days_read_paper_news == "5. Five days" ~ 5,
                                     days_read_paper_news == "6. Six days" ~ 6,
                                     days_read_paper_news == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
      mutate(days_listened_radio_news = case_when(days_listened_radio_news == "0. None" ~ 0,
                                     days_listened_radio_news == "1. One day" ~ 1,
                                     days_listened_radio_news == "2. Two days" ~ 2,
                                     days_listened_radio_news == "3. Three days" ~ 3,
                                     days_listened_radio_news == "4. Four days" ~ 4,
                                     days_listened_radio_news == "5. Five days" ~ 5,
                                     days_listened_radio_news == "6. Six days" ~ 6,
                                     days_listened_radio_news == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
  mutate(days_read_socmedia_news = case_when(days_read_socmedia_news == "0. None" ~ 0,
                                     days_read_socmedia_news == "1. One day" ~ 1,
                                     days_read_socmedia_news == "2. Two days" ~ 2,
                                     days_read_socmedia_news == "3. Three days" ~ 3,
                                     days_read_socmedia_news == "4. Four days" ~ 4,
                                     days_read_socmedia_news == "5. Five days" ~ 5,
                                     days_read_socmedia_news == "6. Six days" ~ 6,
                                     days_read_socmedia_news == "7. Seven days" ~ 7,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "1. Less than 1st grade" ~ 0,
                                     education == "2. 1st, 2nd, 3rd or 4th grade" ~ 1,
                                     education == "3. 5th or 6th grade" ~ 2,
                                     education == "4. 7th or 8th grade" ~ 3,
                                     education == "5. 9th grade" ~ 5,
                                     education == "6. 10th grade" ~ 7,
                                     education == "7. 11th grade" ~ 9,
                                     education == "8. 12th grade no diploma" ~ 11,
                                     education == "9. High school graduate- high school diploma or equivalent (for example: GED)" ~ 15,
                                     education == "10. Some college but no degree" ~ 17,
                                     education == "11. Associate degree in college - occupational /vocational program" ~ 20,
                                     education == "12. Associate degree in college -- academic program" ~ 20,
                                     education == "13. Bachelor's degree (for example: BA, AB, BS)" ~ 25,
                                     education == "14. Master's degree (for example: MA, MS, MENG, MED, MSW, MBA) " ~ 28,
                                     education == "15. Professional school degree (for example: MD, DDS, DVM, LLB, JD)" ~ 31,
                                     education == "16. Doctorate degree (for example: PHD, EDD)" ~ 35,
                                     TRUE ~ NA_real_)) %>%
   mutate(age = case_when(age == "01. Age group 17-20" ~ 0,
                                     age == "02. Age group 21-24" ~ 1,
                                     age == "03. Age group 25-29" ~ 3,
                                     age == "04. Age group 30-34" ~ 6,
                                     age == "05. Age group 35-39" ~ 9,
                                     age == "06. Age group 40-44" ~ 12,
                                     age == "07. Age group 45-49" ~ 15,
                                     age == "08. Age group 50-54" ~ 18,
                                     age == "09. Age group 55-59" ~ 21,
                                     age == "10. Age group 60-64" ~ 24,
                                     age == "11. Age group 65-69" ~ 27,
                                     age == "12. Age group 70-74" ~ 30,
                                     age == "13. Age group 75 or older"  ~ 35,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "01. White" ~ "White",
                                     race == "02. Black or African-American" ~ "Black",
                                     race == "04. Asian" ~ "Asian",
                                     race == "05. Native Hawaiian or other Pacific Islander" ~ "Asian",
                                     race == "03. American Indian or Alaska Native" ~ "Native American",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "1. Democrat" ~ "Democrat",
                                     party_id == "2. Republican" ~ "Republican",
                                     party_id == "3. Independent" ~ "Independent",
                                     TRUE ~ NA_character_))



twelve.china.mil.glm <- glm(china_mil_scale ~ days_read_internet_news + days_watched_tv_news + days_read_paper_news + days_listened_radio_news + days_read_socmedia_news + education + age + race + party_id,
                     data = anes_2012, family = "binomial")

summary(twelve.china.mil.glm)

twelve.china.econ.glm <- glm(china_econ_scale ~ days_read_internet_news + days_watched_tv_news + days_read_paper_news + days_listened_radio_news + days_read_socmedia_news + education + age + race + party_id,
                     data = anes_2012, family = "binomial")

summary(twelve.china.econ.glm)
```
```{r}
chicago_2016 <- 
read_sav("2016public.sav") %>%
  as_factor() %>%
  select(Q5_23, Q5_24, Q45_6, Q50_5, 
         PPETHM, PPEDUCAT, PPAGE, Q1010, Q2_2,Q2_4) %>%
  rename(Q5_23 = china_econ_threat, Q5_24 = china_mil_threat, 
         Q45_6 = china_temp_therm, Q50_5 = china_influence, 
         PPEDUCAT = education, PPAGE = age, 
         PPETHM = race, Q1010 = party_id, Q2_2 = natl_news_interest,
         Q2_4 = usforeignaffairs_news_interest) %>%
  mutate(year = 2016) %>%
  mutate(china_mil_scale = case_when(china_mil_threat == "Critical threat" ~ 1,
                                     china_mil_threat == "Important but not critical threat" ~ 1,
                                     china_mil_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(china_econ_scale = case_when(china_econ_threat == "Critical threat" ~ 1,
                                     china_econ_threat == "Important but not critical threat" ~ 1,
                                     china_econ_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
  mutate(natl_news_interest = case_when(natl_news_interest == "Very interested" ~ 3,
                                     natl_news_interest == "Somewhat interested" ~ 2,
                                     natl_news_interest == "Hardly interested" ~ 1,
                                     natl_news_interest == "Don't follow the news" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(usforeignaffairs_news_interest = case_when(usforeignaffairs_news_interest == "Very interested" ~ 3,
                                     usforeignaffairs_news_interest == "Somewhat interested" ~ 2,
                                     usforeignaffairs_news_interest == "Hardly interested" ~ 1,
                                     usforeignaffairs_news_interest == "Don't follow the news" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate_at(vars(age, china_influence, china_temp_therm), as.numeric)
  



sixteen.chicago.mil.glm <- glm(china_mil_scale ~ natl_news_interest + usforeignaffairs_news_interest + education + age + race + party_id, data = chicago_2016, family = "binomial")

summary(sixteen.chicago.mil.glm)

sixteen.chicago.econ.glm <- glm(china_econ_scale ~ natl_news_interest + usforeignaffairs_news_interest + education + age + race + party_id, data = chicago_2016, family = "binomial")

summary(sixteen.chicago.econ.glm)

sixteen.chicago.temp.lm <- lm(china_temp_therm ~ natl_news_interest + usforeignaffairs_news_interest + education + age + race + party_id, data = chicago_2016)

summary(sixteen.chicago.temp.lm)

sixteen.chicago.influence.lm <- lm(china_influence ~ natl_news_interest + usforeignaffairs_news_interest + education + age + race + party_id, data = chicago_2016)

summary(sixteen.chicago.influence.lm)
```

```{r}
chicago_2017 <- 
read_sav("2017public.sav") %>%
  as_factor() %>%
  select(Q2B, Q130_9, Q12_2, Q50_5, Q80_2, Q5_NEW_5_3,
         PPETHM, PPEDUCAT, PPAGE, Q1010) %>%
  rename(Q2B = main_media_source, Q130_9 = trust_media_do_good, 
         Q12_2 = china_world_responsible, Q50_5 = china_influence, 
         Q80_2 = china_fair_trade, Q5_NEW_5_3 = china_rise_threat,
         PPEDUCAT = education, PPAGE = age, 
         PPETHM = race, Q1010 = party_id) %>%
  mutate(year = 2016) %>%
  mutate(china_fair_trade_scale = case_when(china_fair_trade == "Practice unfair trade" ~ 1,
                                     china_fair_trade == "Practice fair trade" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(china_rise_threat_scale = case_when(china_rise_threat == "Critical threat" ~ 1,
                                     china_rise_threat == "Important but not critical threat" ~ 1,
                                     china_rise_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
       mutate(main_media_source = case_when(main_media_source == "Newspapers and news magazines" ~ "Newspapers and news magazines",
                                     main_media_source == "Radio" ~ "Radio",
                                     main_media_source == "Network TV news broadcasts (For example: ABC, CBS, or NBC)" ~ "Network TV news broadcasts (For example: ABC, CBS, or NBC)",
                                     main_media_source == "Cable TV news broadcasts (For example: CNN, Fox News, or MSNBC)" ~ "Cable TV news broadcasts (For example: CNN, Fox News, or MSNBC)",
                                     main_media_source == "Blogs and other websites" ~ "Blogs and other websites",
                                     main_media_source == "Facebook, Twitter and other social media" ~ "Facebook, Twitter and other social media",
                                     TRUE ~ NA_character_)) %>%
         mutate(trust_media_do_good = case_when(trust_media_do_good == "A great deal" ~ "A great deal",
                                     trust_media_do_good == "A fair amount" ~ "A fair amount",
                                     trust_media_do_good == "Not very much" ~ "Not very much",
                                     trust_media_do_good == "No confidence at all" ~ "No confidence at all",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
  mutate_at(vars(age, china_influence, china_world_responsible), as.numeric)
  
# chicago_2017$main_media_source <- relevel(chicago_2017$main_media_source, "Newspapers and news magazines")
chicago_2017$main_media_source <- factor(chicago_2017$main_media_source, levels = c("Newspapers and news magazines", "Radio", "Network TV news broadcasts (For example: ABC, CBS, or NBC)", "Cable TV news broadcasts (For example: CNN, Fox News, or MSNBC)", "Blogs and other websites", "Facebook, Twitter and other social media" ~ "Facebook, Twitter and other social media"))

chicago_2017$trust_media_do_good <- factor(chicago_2017$trust_media_do_good, levels = c("A great deal", "A fair amount", "Not very much", "No confidence at all"))

seventeen.chicago.trade.glm <- glm(china_fair_trade ~ main_media_source + education + age + race + party_id, data = chicago_2017, family = "binomial")

summary(seventeen.chicago.trade.glm)

seventeen.chicago.threat.glm <- glm(china_rise_threat_scale ~ main_media_source + education + age + race + party_id, data = chicago_2017, family = "binomial")

summary(seventeen.chicago.threat.glm)

seventeen.chicago.responsible.lm <- lm(china_world_responsible ~ main_media_source + education + age + race + party_id, data = chicago_2017)

summary(seventeen.chicago.responsible.lm)

seventeen.chicago.influence.lm <- lm(china_influence ~ main_media_source + education + age + race + party_id, data = chicago_2017)

summary(seventeen.chicago.influence.lm)

two.seventeen.chicago.trade.glm <- glm(china_fair_trade ~ trust_media_do_good + education + age + race + party_id, data = chicago_2017, family = "binomial")

summary(two.seventeen.chicago.trade.glm)

two.seventeen.chicago.threat.glm <- glm(china_rise_threat_scale ~ trust_media_do_good + education + age + race + party_id, data = chicago_2017, family = "binomial")

summary(two.seventeen.chicago.threat.glm)

two.seventeen.chicago.responsible.lm <- lm(china_world_responsible ~ trust_media_do_good + education + age + race + party_id, data = chicago_2017)

summary(two.seventeen.chicago.responsible.lm)

two.seventeen.chicago.influence.lm <- lm(china_influence ~ trust_media_do_good + education + age + race + party_id, data = chicago_2017)

summary(two.seventeen.chicago.influence.lm)
```

```{r}
chicago_2018 <- 
read_sav("2018public.sav") %>%
  as_factor() %>%
  select(Q450b_2, Q450C_2, Q144_1, Q30_2, Q30_14,Q50_5, Q376, Q73_5, Q5_NEW_3, Q5_NEW_41, Q2_2, Q2_4,  
         PPETHM, PPEDUCAT, PPAGE, Q1010, Q130_9,PPGENDER) %>%
  rename(Q2_2 = national_news_interest, Q130_9 = trust_media_do_good, Q2_4 = us_relations_news_interest,
         Q144_1 = china_intl_respect, Q50_5 = china_influence, Q376 = us_china_partnership,
         Q450b_2 = china_economic_relationship_importance, Q450C_2 = china_security_importance,
         Q5_NEW_3 = china_rise_threat, Q5_NEW_41 = china_trade_war_threat,
         Q30_2 = war_with_china_taiwan, Q30_14 = war_with_china_japan, Q73_5 = china_approval_nkoreanukes,
         PPEDUCAT = education, PPAGE = age, PPGENDER = gender,
         PPETHM = race, Q1010 = party_id) %>%
  mutate(year = 2018) %>%
  mutate(us_china_partnership = case_when(us_china_partnership == "Building up our strong relations with traditional allies like South Korea and Japan [...]" ~ 1,
                                     us_china_partnership == "Building a new partnership with China [...]" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(china_rise_threat_scale = case_when(china_rise_threat == "Critical threat" ~ 1,
                                     china_rise_threat == "Important but not critical threat" ~ 1,
                                     china_rise_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
    mutate(china_trade_war_scale = case_when(china_trade_war_threat == "Critical threat" ~ 1,
                                     china_trade_war_threat == "Important but not critical threat" ~ 1,
                                     china_trade_war_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(china_intl_respect_scale = case_when(china_intl_respect == "Respected more" ~ 0,
                                     china_intl_respect == "Respected less" ~ 1,
                                     china_intl_respect == "Respected about as much as ten years ago" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(china_approval_nkoreanukes_scale = case_when(china_approval_nkoreanukes == "Necessary" ~ 0,
                                     china_approval_nkoreanukes == "Preferable but not necessary" ~ 1,
                                     china_approval_nkoreanukes == "Neither preferable nor necessary" ~ 1,
                                     TRUE ~ NA_real_)) %>%
   mutate(war_with_china_taiwan_scale = case_when(war_with_china_taiwan == "Favor" ~ 1,
                                     war_with_china_taiwan == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(war_with_china_japan_scale = case_when(war_with_china_japan == "Favor" ~ 1,
                                     war_with_china_japan == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
       mutate(national_news_interest = case_when(national_news_interest == "Very interested" ~ "Very interested",
                                     national_news_interest == "Somewhat interested" ~ "Somewhat interested",
                                     national_news_interest == "Hardly interested" ~ "Hardly interested",
                                     national_news_interest == "Don't follow the news" ~ "Don't follow the news",
                                     TRUE ~ NA_character_)) %>%
         mutate(us_relations_news_interest = case_when(us_relations_news_interest == "Very interested" ~ "Very interested",
                                     us_relations_news_interest == "Somewhat interested" ~ "Somewhat interested",
                                     us_relations_news_interest == "Hardly interested" ~ "Hardly interested",
                                     us_relations_news_interest == "Don't follow the news" ~ "Don't follow the news",
                                     TRUE ~ NA_character_)) %>%
         mutate(trust_media_do_good = case_when(trust_media_do_good == "A great deal" ~ "A great deal",
                                     trust_media_do_good == "A fair amount" ~ "A fair amount",
                                     trust_media_do_good == "Not very much" ~ "Not very much",
                                     trust_media_do_good == "No confidence at all" ~ "No confidence at all",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ "Independent")) %>%
       mutate(gender = case_when(gender == "Male" ~ "Male",
                                     gender == "Female" ~ "Female",
                                     TRUE ~ NA_character_)) %>%
  mutate_at(vars(age, china_influence, china_economic_relationship_importance, china_security_importance), as.numeric)
  
# chicago_2017$main_media_source <- relevel(chicago_2017$main_media_source, "Newspapers and news magazines")
chicago_2018$national_news_interest <- factor(chicago_2018$national_news_interest, levels = c("Very interested", "Somewhat interested", "Hardly interested", "Don't follow the news"))

chicago_2018$us_relations_news_interest <- factor(chicago_2018$us_relations_news_interest, levels = c("Very interested", "Somewhat interested", "Hardly interested", "Don't follow the news"))


chicago_2018$trust_media_do_good <- factor(chicago_2018$trust_media_do_good, levels = c("A great deal", "A fair amount", "Not very much", "No confidence at all"))

eighteen.chicago.partnership.glm <- glm(us_china_partnership ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.rise.glm)

two.eighteen.chicago.partnership.glm <- glm(us_china_partnership ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.rise.glm)

three.eighteen.chicago.partnership.glm <- glm(us_china_partnership ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.partnership.glm)

eighteen.chicago.rise.glm <- glm(china_rise_threat_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.rise.glm)

two.eighteen.chicago.rise.glm <- glm(china_rise_threat_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.rise.glm)

three.eighteen.chicago.rise.glm <- glm(china_rise_threat_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.rise.glm)

eighteen.chicago.tradewar.glm <- glm(china_trade_war_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.tradewar.glm)

two.eighteen.chicago.tradewar.glm <- glm(china_trade_war_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.tradewar.glm)

three.eighteen.chicago.tradewar.glm <- glm(china_trade_war_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.tradewar.glm)

eighteen.chicago.respect.glm <- glm(china_intl_respect_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.respect.glm)

two.eighteen.chicago.respect.glm <- glm(china_intl_respect_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.respect.glm)

three.eighteen.chicago.respect.glm <- glm(china_intl_respect_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.respect.glm)

eighteen.chicago.koreanukes.glm <- glm(china_approval_nkoreanukes_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.koreanukes.glm)

two.eighteen.chicago.koreanukes.glm <- glm(china_approval_nkoreanukes_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.koreanukes.glm)

three.eighteen.chicago.koreanukes.glm <- glm(china_approval_nkoreanukes_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.koreanukes.glm)

eighteen.chicago.wartaiwan.glm <- glm(war_with_china_taiwan_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.wartaiwan.glm)

two.eighteen.chicago.wartaiwan.glm <- glm(war_with_china_taiwan_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.wartaiwan.glm)

three.eighteen.chicago.wartaiwan.glm <- glm(war_with_china_taiwan_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.wartaiwan.glm)

eighteen.chicago.warjapan.glm <- glm(war_with_china_japan_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(eighteen.chicago.warjapan.glm)

two.eighteen.chicago.warjapan.glm <- glm(war_with_china_japan_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(two.eighteen.chicago.warjapan.glm)

three.eighteen.chicago.warjapan.glm <- glm(war_with_china_japan_scale ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018, family = "binomial")

summary(three.eighteen.chicago.warjapan.glm)

eighteen.chicago.influence.lm <- lm(china_influence ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(eighteen.chicago.influence.lm)

two.eighteen.chicago.influence.lm <- lm(china_influence ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(two.eighteen.chicago.influence.lm)

three.eighteen.chicago.influence.lm <- lm(china_influence ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018)

summary(three.eighteen.chicago.influence.lm)

eighteen.chicago.econrelationship.lm <- lm(china_economic_relationship_importance ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(eighteen.chicago.econrelationship.lm)

two.eighteen.chicago.econrelationship.lm <- lm(china_economic_relationship_importance ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(two.eighteen.chicago.econrelationship.lm)

three.eighteen.chicago.econrelationship.lm <- lm(china_economic_relationship_importance ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018)

summary(three.eighteen.chicago.econrelationship.lm)

eighteen.chicago.securityrelationship.lm <- lm(china_security_importance ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(eighteen.chicago.securityrelationship.lm)

two.eighteen.chicago.securityrelationship.lm <- lm(china_security_importance ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2018)

summary(two.eighteen.chicago.securityrelationship.lm)

three.eighteen.chicago.securityrelationship.lm <- lm(china_security_importance ~ trust_media_do_good + education + age + race + party_id + gender, data = chicago_2018)

summary(three.eighteen.chicago.securityrelationship.lm)
```


```{r}
chicago_2015 <- 
read_sav("2015public.sav") %>%
  as_factor() %>%
  select(Q20_NEW_B, Q12_NEW_B, Q325B_D, Q30_B, Q30_H, Q450_B, Q330C, Q332, Q2_NEW_B, Q2_NEW_D, PPETHM, PPEDUCAT, PPAGE, Q1010, PPGENDER) %>%
  rename(Q2_NEW_B = national_news_interest, Q2_NEW_D = us_relations_news_interest,
         Q20_NEW_B = china_leadership, Q12_NEW_B = china_world_problems, Q325B_D = china_asia_problems,
         Q30_B = war_with_china_taiwan, Q30_H = war_with_china_japan, Q450_B = us_china_relationship_importance,
         Q330C = us_china_partner, Q332 = improve_relations_strategy,
         PPEDUCAT = education, PPAGE = age, PPGENDER = gender,
         PPETHM = race, Q1010 = party_id) %>%
  mutate(year = 2015) %>%
   mutate(war_with_china_taiwan_scale = case_when(war_with_china_taiwan == "Favor" ~ 1,
                                     war_with_china_taiwan == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(war_with_china_japan_scale = case_when(war_with_china_japan == "Favor" ~ 1,
                                     war_with_china_japan == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
     mutate(national_news_interest = case_when(national_news_interest == "Very interested" ~ "Very interested",
                                     national_news_interest == "Somewhat interested" ~ "Somewhat interested",
                                     national_news_interest == "Hardly interested" ~ "Hardly interested",
                                     national_news_interest == "Don't follow the news" ~ "Don't follow the news",
                                     TRUE ~ NA_character_)) %>%
     mutate(us_relations_news_interest = case_when(us_relations_news_interest == "Very interested" ~ "Very interested",
                                     us_relations_news_interest == "Somewhat interested" ~ "Somewhat interested",
                                     us_relations_news_interest == "Hardly interested" ~ "Hardly interested",
                                     us_relations_news_interest == "Don't follow the news" ~ "Don't follow the news",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
         mutate(gender = case_when(gender == "Male" ~ "Male",
                                     gender == "Female" ~ "Female",
                                     TRUE ~ NA_character_)) %>%
  mutate_at(vars(age, china_leadership, china_world_problems, china_asia_problems, us_china_relationship_importance, us_china_partner), as.numeric)
  
# chicago_2017$main_media_source <- relevel(chicago_2017$main_media_source, "Newspapers and news magazines")

chicago_2015$national_news_interest <- factor(chicago_2015$national_news_interest, levels = c("Very interested", "Somewhat interested", "Hardly interested", "Don't follow the news"))

chicago_2015$us_relations_news_interest <- factor(chicago_2015$us_relations_news_interest, levels = c("Very interested", "Somewhat interested", "Hardly interested", "Don't follow the news"))

fifteen.chicago.wartaiwan.glm <- glm(war_with_china_taiwan_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015, family = "binomial")

summary(fifteen.chicago.wartaiwan.glm)

two.fifteen.chicago.wartaiwan.glm <- glm(war_with_china_taiwan_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015, family = "binomial")

summary(two.fifteen.chicago.wartaiwan.glm)

fifteen.chicago.warjapan.glm <- glm(war_with_china_japan_scale ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015, family = "binomial")

summary(fifteen.chicago.warjapan.glm)

two.fifteen.chicago.warjapan.glm <- glm(war_with_china_japan_scale ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015, family = "binomial")

summary(two.fifteen.chicago.warjapan.glm)

fifteen.chicago.leadership.lm <- lm(china_leadership ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(fifteen.chicago.leadership.lm)

two.fifteen.chicago.leadership.lm <- lm(china_leadership ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(two.fifteen.chicago.leadership.lm)

fifteen.chicago.worldproblems.lm <- lm(china_world_problems ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(fifteen.chicago.worldproblems.lm)

two.fifteen.chicago.worldproblems.lm <- lm(china_world_problems ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(two.fifteen.chicago.worldproblems.lm)

fifteen.chicago.asiaproblems.lm <- lm(china_asia_problems ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(fifteen.chicago.asiaproblems.lm)

two.fifteen.chicago.asiaproblems.lm <- lm(china_asia_problems ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(two.fifteen.chicago.asiaproblems.lm)

fifteen.chicago.uschinarelations.lm <- lm(us_china_relationship_importance ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(fifteen.chicago.uschinarelations.lm)

two.fifteen.chicago.uschinarelations.lm <- lm(us_china_relationship_importance ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(two.fifteen.chicago.uschinarelations.lm)

fifteen.chicago.chinapartner.lm <- lm(us_china_partner ~ national_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(fifteen.chicago.chinapartner.lm)

two.fifteen.chicago.chinapartner.lm <- lm(us_china_partner ~ us_relations_news_interest + education + age + race + party_id + gender, data = chicago_2015)

summary(two.fifteen.chicago.chinapartner.lm)
```

```{r}
chicago_2014 <- 
read_sav("2014public.sav") %>%
  as_factor() %>%
  select(q455_2, q340, q350, q376, q45_06, q50_5, q125_8, q120_8, ppethm, ppeducat, ppage, q1010, ppgender) %>%
  rename(q125_8 = media_should_influence, q120_8 = media_does_influence,
         q455_2 = china_us_rivals, q340 = china_economy_good, q350 = us_china_power_counter,
         q376 = us_asia_policy, q45_06 = china_temp_therm, q50_5 = china_influence,
         ppeducat = education, ppage = age, ppgender = gender,
         ppethm = race, q1010 = party_id) %>%
  mutate(year = 2014) %>%
   mutate(china_us_rivals = case_when(china_us_rivals == "Mostly rivals" ~ 1,
                                     china_us_rivals == "Mostly partners" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(china_economy_good = case_when(china_economy_good == "Mostly positive" ~ 1,
                                     china_economy_good == "Mostly negative" ~ 0,
                                     china_economy_good == "Equally positive and negative" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(us_china_power_counter = case_when(us_china_power_counter == "Undertake friendly cooperation and engagement with China" ~ 0,
                                     us_china_power_counter == "Actively work to limit the growth of China's power" ~ 1,
                                     TRUE ~ NA_real_)) %>%
  mutate(us_asia_policy = case_when(us_asia_policy == "Building a new partnership with China, even if this might diminish our relations with our traditional allies" ~ 0,
                                     us_asia_policy == "Building up our strong relations with traditional allies like South Korea and Japan, even if this might diminish our rel" ~ 1,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
         mutate(gender = case_when(gender == "Male" ~ "Male",
                                     gender == "Female" ~ "Female",
                                     TRUE ~ NA_character_)) %>%
  mutate_at(vars(age, china_temp_therm, media_should_influence, china_influence, media_does_influence), as.numeric)

fourteen.chicago.rivals.glm <- glm(china_us_rivals ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(fourteen.chicago.rivals.glm)

two.fourteen.chicago.rivals.glm <- glm(china_us_rivals ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(two.fourteen.chicago.rivals.glm)

fourteen.chicago.economygood.glm <- glm(china_economy_good ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(fourteen.chicago.economygood.glm)

two.fourteen.chicago.economygood.glm <- glm(china_economy_good ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(two.fourteen.chicago.economygood.glm)


fourteen.chicago.power.glm <- glm(us_china_power_counter ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(fourteen.chicago.power.glm)

two.fourteen.chicago.power.glm <- glm(us_china_power_counter ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(two.fourteen.chicago.power.glm)

fourteen.chicago.asiapolicy.glm <- glm(us_asia_policy ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(fourteen.chicago.asiapolicy.glm)

two.fourteen.chicago.asiapolicy.glm <- glm(us_asia_policy ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014, family = "binomial")

summary(two.fourteen.chicago.asiapolicy.glm)

fourteen.chicago.temptherm.lm <- lm(china_temp_therm ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014)

summary(fourteen.chicago.temptherm.lm)

two.fourteen.chicago.temptherm.lm <- lm(china_temp_therm ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014)

summary(two.fourteen.chicago.temptherm.lm)

fourteen.chicago.influence.lm <- lm(china_influence ~ media_should_influence + education + age + race + party_id + gender, data = chicago_2014)

summary(fourteen.chicago.influence.lm)

two.fourteen.chicago.influence.lm <- lm(china_influence ~ media_does_influence + education + age + race + party_id + gender, data = chicago_2014)

summary(two.fourteen.chicago.influence.lm)
```

```{r}
chicago_2012 <- 
read_sav("2012public.sav") %>%
  as_factor() %>%
  select(Q5_3, Q30_2, Q80_2, Q455_2, Q350, Q50_5, PPEDUCAT, PPAGE, PPGENDER, PPETHM, Q1010, Q2_A, Q2_B, Q2_C, Q2_D, Q2_E) %>%
  rename(Q5_3 = china_growth_threat, Q30_2 = china_invade_taiwan,
         Q80_2 = china_fair_trade, Q455_2 = us_china_rivals, Q350 = china_policy,
         Q50_5 = china_influence,
         PPEDUCAT = education, PPAGE = age, PPGENDER = gender,
         PPETHM = race, Q1010 = party_id, Q2_A = newspaper_media, Q2_B = radio_media, Q2_C = networktv_media, Q2_D = cabletv_media, Q2_E = onlineblog_media) %>%
  mutate(year = 2012) %>%
   mutate(china_growth_threat = case_when(china_growth_threat == "Critical threat" ~ 1,
                                     china_growth_threat == "Important but not critical threat" ~ 0,
                                     china_growth_threat == "Not an important threat" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(china_invade_taiwan = case_when(china_invade_taiwan == "Favor" ~ 1,
                                     china_invade_taiwan == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(china_fair_trade = case_when(china_fair_trade == "Practice fair trade" ~ 0,
                                     china_fair_trade == "Practice unfair trade" ~ 1,
                                     TRUE ~ NA_real_)) %>%
  mutate(us_china_rivals = case_when(us_china_rivals == "Mostly rivals" ~ 1,
                                     us_china_rivals == "Mostly partners" ~ 0,
                                     TRUE ~ NA_real_)) %>%
    mutate(china_policy = case_when(china_policy == "Undertake friendly cooperation and engagement with China" ~ 0,
                                     china_policy == "Actively work to limit the growth of China's power" ~ 1,
                                     TRUE ~ NA_real_)) %>%
  mutate(education = case_when(education == "Less than high school" ~ 0,
                                     education == "High school" ~ 4,
                                     education == "Some college" ~ 6,
                                     education == "Bachelor's degree or higher" ~ 10,
                                     TRUE ~ NA_real_)) %>%
     mutate(race = case_when(race == "White, Non-Hispanic" ~ "White",
                                     race == "Black, Non-Hispanic" ~ "Black",
                                     race == "Other, Non-Hispanic" ~ "Other",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "2+ Races, Non-Hispanic" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
       mutate(party_id = case_when(party_id == "Democrat" ~ "Democrat",
                                     party_id == "Republican" ~ "Republican",
                                     party_id == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
         mutate(gender = case_when(gender == "Male" ~ "Male",
                                     gender == "Female" ~ "Female",
                                     TRUE ~ NA_character_)) %>%
         mutate(newspaper_media = case_when(newspaper_media == "Almost every day" ~ 8,
                                     newspaper_media == "About 2-3 times a week" ~ 4,
                                     newspaper_media == "About once a week" ~ 2,
                                     newspaper_media == "Less than once a week" ~ 1,
                                     newspaper_media == "Never" ~ 0,
                                     TRUE ~ NA_real_)) %>%
           mutate(radio_media = case_when(radio_media == "Almost every day" ~ 8,
                                     radio_media == "About 2-3 times a week" ~ 4,
                                     radio_media == "About once a week" ~ 2,
                                     radio_media == "Less than once a week" ~ 1,
                                     radio_media == "Never" ~ 0,
                                     TRUE ~ NA_real_)) %>%
             mutate(networktv_media = case_when(networktv_media == "Almost every day" ~ 8,
                                     networktv_media == "About 2-3 times a week" ~ 4,
                                     networktv_media == "About once a week" ~ 2,
                                     networktv_media == "Less than once a week" ~ 1,
                                     networktv_media == "Never" ~ 0,
                                     TRUE ~ NA_real_)) %>%
             mutate(cabletv_media = case_when(cabletv_media == "Almost every day" ~ 8,
                                     cabletv_media == "About 2-3 times a week" ~ 4,
                                     cabletv_media == "About once a week" ~ 2,
                                     cabletv_media == "Less than once a week" ~ 1,
                                     cabletv_media == "Never" ~ 0,
                                     TRUE ~ NA_real_)) %>%  
               mutate(onlineblog_media = case_when(onlineblog_media == "Almost every day" ~ 8,
                                     onlineblog_media == "About 2-3 times a week" ~ 4,
                                     onlineblog_media == "About once a week" ~ 2,
                                     onlineblog_media == "Less than once a week" ~ 1,
                                     onlineblog_media == "Never" ~ 0,
                                     TRUE ~ NA_real_)) %>%  
  mutate_at(vars(age, china_influence), as.numeric)

twelve.chicago.growth.glm <- glm(china_growth_threat ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012, family = "binomial")

summary(twelve.chicago.growth.glm)

twelve.chicago.taiwanwar.glm <- glm(china_invade_taiwan ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012, family = "binomial")

summary(twelve.chicago.taiwanwar.glm)

twelve.chicago.fairtrade.glm <- glm(china_fair_trade ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012, family = "binomial")

summary(twelve.chicago.fairtrade.glm)

twelve.chicago.rivals.glm <- glm(us_china_rivals ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012, family = "binomial")

summary(twelve.chicago.rivals.glm)

twelve.chicago.chinapolicy.glm <- glm(china_policy ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012, family = "binomial")

summary(twelve.chicago.chinapolicy.glm)

twelve.chicago.chinainfluence.lm <- lm(china_influence ~ newspaper_media + radio_media + networktv_media + cabletv_media + onlineblog_media + education + age + race + party_id + gender, data = chicago_2012)

summary(twelve.chicago.chinainfluence.lm)
```



